Bump nixpkgs to 25.11 for age >=1.3.0
nixpkgs 25.11 also needs nix >=2.18, thus bumping the actions versions.

Also handling:

```
error: 'nixosTest' has been renamed to/replaced by 'testers.nixosTest'
```

and

```
error:
       nix-darwin now uses release branches that correspond to Nixpkgs releases.
       The nix-darwin and Nixpkgs branches in use must match, but you are currently
       using nix-darwin 26.05 with Nixpkgs 25.11.

On macOS, you should use either the `nixpkgs-unstable` or
       `nixpkgs-YY.MM-darwin` branches of Nixpkgs. These correspond to the
       `master` and `nix-darwin-YY.MM` branches of nix-darwin, respectively. Check
       <https://status.nixos.org/> for the currently supported Nixpkgs releases.
```

and

```
evaluation warning: user1 profile: You are using

                      Home Manager version 26.05 and
                      Nixpkgs version 25.11.

Using mismatched versions is likely to cause errors and unexpected
                    behavior. It is therefore highly recommended to use a release of Home
                    Manager that corresponds with your chosen release of Nixpkgs.
```

and

```
error:
       Failed assertions:
       - The `system.activationScripts.extraUserActivation` option has
       been removed, as all activation now takes place as `root`. Please
       restructure your custom activation scripts appropriately,
       potentially using `sudo` if you need to run commands as a user.
```

Also update darwin CI: remove deprecated activate-user and handle /etc
files for nix-darwin 25.11.